# Tâche 1 - Modèles de langue N-grammes

Cette tâche consiste à construire, avec NLTK, des modèles de langue Ngrammes à partir de titres de chansons et de les utiliser pour accomplir 2 sous-tâches qui sont décrites dans l'énoncé du travail pratique. 

Les fichiers à utiliser pour cette tâche :
- *t1_titres_chansons.txt*: il contient une liste de titres de chansons, un par ligne de texte. Vous utilisez ce fichier pour la construction des modèles de langues N-grammes. 
- *t1_estimation_test.json*: il contient des listes de candidats, chaque liste contenant un seul titre de chanson connu parmi les candidats. 
- *t1_generation_test.json*: il contient des titres incomplets se terminant par des mots masqués.  

Consignes: 
- Ne pas modifier les fonctions *load_titles* et *load_tests*.
- Utilisez la variable *models* pour conserver les modèles après entraînement. 
- Ne pas modifier la signature des fonctions *train_models* et *complete_title*.
- Des modifications aux signatures de fonctions entraîneront des pénalités dans la correction. 
- Vous pouvez ajouter des cellules au *notebook* et ajouter toutes les fonctions utilitaires que vous voulez.

## Section 1 - Lecture des fichiers de données (titres de chansons et tests)

On définit ici 2 fonctions pour lire les fichiers d'entraînement et de test.

In [1]:
import json


titres_fn = "./data/t1_titres_chansons.txt"    
test_estimation_fn = './data/t1_estimation_test.json'  
test_generation_fn = './data/t1_generation_test.json'  


def load_titles(filename):
    with open(filename, 'r', encoding='utf-8') as f:
        raw_lines = f.readlines()
    return [x.strip() for x in raw_lines]


def load_tests(filename):
    with open(filename, 'r', encoding='utf-8') as fp:
        test_data = json.load(fp)
    return test_data

In [2]:
titles = load_titles(titres_fn)

Quelques informations à propos des titres:

In [3]:
print("Nombre de titres pour l'entraînement: {}".format(len(titles)))

Nombre de titres pour l'entraînement: 572

On monte également les 2 fichiers de test pour visualiser leur contenu.

In [4]:
import pandas as pd

def get_dataframe(tests):
    return pd.DataFrame.from_dict(tests, orient='columns', dtype=None, columns=None)

In [5]:
tests_estimation = load_tests(test_estimation_fn)

In [6]:
df = get_dataframe(tests_estimation)
pd.set_option("display.max_colwidth", 120)
display(df)

,Candidates,Song
0,"[i want to hold and love, i want to hold something, i want to hold your hand]",i want to hold your hand
1,"[let it be, let me be, let it roll]",let it be
2,"[i want to know the world, i want to love the way you lie, i want to know what love is]",i want to know what love is
3,"[i will survive, i will be there, i will follow and wait]",i will survive
4,"[i will wait, i will eat, i will break free]",i will wait
5,"[i gotta feeling, i gotta rock you, i gotta a feeling to rock you]",i gotta feeling
6,"[i want to break free, i want to break the mold, i want to break my mold free]",i want to break free
7,"[we will rock you, i will rock you, she will rock you]",we will rock you
8,"[i kissed a girl, i kissed a boy, i kissed nobody]",i kissed a girl
9,"[i believe i can fly, i believe i can rock, i believe i can wake up]",i believe i can fly
10,"[i am a man, i am a women, i am a person]",i am a man
11,"[you are so beautiful, i am so beautiful, we are so beautiful]",you are so beautiful
12,"[let the good times roll, let the good times rock, let the bad times roll]",let the good times roll
13,"[let's have a party, let's dream a party, let's have a party and let it roll]",let's have a party
14,"[we are family, we are cousins, we are sisters]",we are family
15,"[we didn't start the fire, we didn't want the fire, we didn't break the fire]",we didn't start the fire
16,"[love shack, love you, love you and me]",love shack
17,"[love the way you lie, dream the way you lie, feel the way you lie]",love the way you lie
18,"[my heart will go on, my heart will beat and go on and on, my heart will tell me]",my heart will go on
19,"[the sound of silence, the sound breaks the silence, the sound]",the sound of silence

In [7]:
tests_generation = load_tests(test_generation_fn)

df = get_dataframe(tests_generation)
pd.set_option("display.max_colwidth", 100)
display(df)

                          Masked                         Song
0                       love ***                   love shack
1        i want to hold your ***     i want to hold your hand
2         i want to hold *** ***     i want to hold your hand
3         i want *** *** *** ***     i want to hold your hand
4                     let it ***                    let it be
5                     i will ***               i will survive
6                    i gotta ***              i gotta feeling
7            i want to break ***         i want to break free
8              i want to *** ***         i want to break free
9             i want *** *** ***         i want to break free
10              we will rock ***             we will rock you
11               we will *** ***             we will rock you
12                i kissed a ***              i kissed a girl
13              i kissed *** ***              i kissed a girl
14           i believe i can ***          i believe i can fly
15           i believe i *** ***          i believe i can fly
16                    i am a ***                   i am a man
17                  i am *** ***                   i am a man
18                you are so ***         you are so beautiful
19               you are *** ***         you are so beautiful
20        let the good times ***      let the good times roll
21          let the good *** ***      let the good times roll
22              let's have a ***           let's have a party
23            let's have *** ***           let's have a party
24             let's *** *** ***           let's have a party
25                    we are ***                we are family
26                    i will ***                  i will wait
27       we didn't start the ***     we didn't start the fire
28       we didn't start *** ***     we didn't start the fire
29          love the way you ***         love the way you lie
30          love the way *** ***         love the way you lie
31               take my *** ***          take my breath away
32          my heart will go ***          my heart will go on
33         my heart will *** ***          my heart will go on
34          my heart *** *** ***          my heart will go on
35              the sound of ***         the sound of silence
36             the sound *** ***         the sound of silence
37  i want to know what love ***  i want to know what love is
38   i want to know what *** ***  i want to know what love is
39    i want to know *** *** ***  i want to know what love is

## Section 2 - Construction des modèles de langue N-grammes. 

La fonction ***train_models*** prend en entrée une liste de titres de chansons et construit trois modèles: unigramme, bigramme et trigramme.

Les modèles sont conservés dans ***models***, un dictionnaire Python qui prend la forme 

<pre>
{
   1: modele_unigramme, 
   2: modele_bigramme, 
   3: modele_trigramme
}
</pre>

avec comme clé la valeur N du modèle et comme valeur le modèle construit par NLTK.

In [8]:
models = {}

In [9]:
def train_models(texts):
    """ Vous ajoutez à partir d'ici le code dont vous avez besoin
        pour construire les différents modèles N-grammes.
        Cette fonction doit construire tous les modèles en une seule passe.
    """

    # Votre code à partir d'ici... Retirez cette ligne pour la remise.


    
    
    # Sauvegarde de vos modèles 
    models[1] = None # A MODIFIER
    models[2] = None # A MODIFIER
    models[3] = None # A MODIFIER

## Section 3 - Estimation - Choix parmi plusieurs candidats

In [10]:
def select_candidate(candidates, n=3):
    """ 
        Cette fonction retourne le candidat retenu ainsi que son score attribué par le modèle.
        
        *candidates* est la liste de passages de textes obtenu à partir du fichier de test. 
        Un seul des passage est un titre de chanson connu. 
        
        Le paramètre n désigne le modèle utilisé.
        1 - unigramme NLTK, 2 - bigramme NLTK, 3 - trigramme NLTK
         
    """

    # Votre code à partir d'ici. Vous pouvez modifier comme bon vous semble. Retirez cette ligne.




    
    best_score = 1   # A MODIFIER
    result = "le soleil dit bonjour aux montagnes"  # A MODIFIER
    return result, best_score

Présentez ici vos résultats et répondez aux questions formulées dans l'énoncé du travail.

## Section 4 - Génération - Compléter les titres de chansons

In [11]:
def complete_title(model, tokenized_seed, nb_words, random_seed=46):
    """
        Génère des mots et les ajoute à la fin du texte tokenisé. 
        Retourne la liste de mots du titre complet (c.-à-d. le *tokenized_seed* + les *nb_words* générés).
        
        model: Le modèle N-gramme utilisé
        tokenized_seed: le titre incomplet, sans les masques, qui a été tokenisé. Par exemple: ["le", "soleil"].
        random_seed: utilisé par NLTK pour la génération de nombre aléatoire. 
        
    """    

    # Votre code à partir d'ici. Vous pouvez modifier comme bon vous semble. Retirez cette ligne. 
    
    
    
    generated = ["le", "soleil", "dit", "bonjour", "aux", "montagnes"]  # A MODIFIER
    return generated

## Section 5 - Partie réservée pour faire nos tests lors de la correction

Merci de ne pas modifier ni retirer cette section du notebook.